### ISSUE TITLE
invalid_request after installation and configuration

### ISSUE THREAD

**Issue by abandin-stratio** [LeisureLink/gce-inventory#3]
Hi:

I got the honor of open the issues section!  I recently installed the module with:

npm install -g gce-inventory

After that i created a /etc/ansible/inventory/.gce-options and i exported it to GCE_OPTIONS variable.
```
---

projectId: xxxxxxxxxxxxxxxxxx
keyFileName: xxxxxxxxxxx

# Limits the zones that are queried.
zones:
  - europe-west1-b

# Specifies how hostvars are composed
#   the JSON Pointers are relative to the source data
hostvars:
# implicit hostvars (don't need defining)
# - name
# - zone:
#   captureRe: '[^/]+(?=/$|$)'
# - ansible_ssh_host: !!calculated - see below!!
  - status:
    # transforms the source value to lowercase
    transform: lowercase
  - network: /networkInterfaces/0/network
    # performs a regex capture against source value
    captureRe: '[^/]+(?=/$|$)'
  - internalIP: /networkInterfaces/0/networkIP
  - externalIP: /networkInterfaces/0/accessConfigs/0/natIP
  - tags: /tags/items
  - metadata: /metadata/items
    # transforms key value pairs to object properties
    transform: objectFromKeyValues
  - machine_type: /machineType
    # performs a regex capture against source value
    captureRe: '[^/]+(?=/$|$)'

# Materializes groups in the output;
#   properties must be defined in hostvars.
groups:
  - zone
  - network:
    # prepends each network
    prepend: network-
  - machine_type
  - tags:
    # prepends each tag
    prepend: 'tag-'
  - status:
    # prepends each status
    prepend: 'status-'

group_vars:
  tag-coreos:
    ansible_ssh_user: core
    ansible_python_interpreter: "PATH=/home/core/bin:$PATH python"

# Established after hostvars are calculated;
#  the JSON Pointer is hostvars relative.
ansible_ssh_host: /externalIP
# ansible_ssh_host: /internalIP

# A simple order-by mechanism.
order:
  - zone
  - tags
  - machine_type
  - status
---
```

When i run the command i get:
```
---
  gce-inventory:load-options checking access to GCE_OPTIONS file from the environment: /etc/ansible/inventory/.gce-options +0ms
  gce-inventory:load-options using GCE_OPTIONS file from the environment: /etc/ansible/inventory/.gce-options +4ms
  gce-inventory:list options: { projectId: 'xxxxxxxxx',
  gce-inventory:list   keyFileName: 'xxxxxxxx',
  gce-inventory:list   zones: [ 'europe-west1-b' ],
  gce-inventory:list   hostvars:
  gce-inventory:list    [ { status: null, transform: 'lowercase' },
  gce-inventory:list      { network: '/networkInterfaces/0/network',
  gce-inventory:list        captureRe: '[^/]+(?=/$|$)' },
  gce-inventory:list      { internalIP: '/networkInterfaces/0/networkIP' },
  gce-inventory:list      { externalIP: '/networkInterfaces/0/accessConfigs/0/natIP' },
  gce-inventory:list      { tags: '/tags/items' },
  gce-inventory:list      { metadata: '/metadata/items',
  gce-inventory:list        transform: 'objectFromKeyValues' },
  gce-inventory:list      { machine_type: '/machineType', captureRe: '[^/]+(?=/$|$)' } ],
  gce-inventory:list   groups:
  gce-inventory:list    [ 'zone',
  gce-inventory:list      { network: null, prepend: 'network-' },
  gce-inventory:list      'machine_type',
  gce-inventory:list      { tags: null, prepend: 'tag-' },
  gce-inventory:list      { status: null, prepend: 'status-' } ],
  gce-inventory:list   group_vars:
  gce-inventory:list    { 'tag-coreos':
  gce-inventory:list       { ansible_ssh_user: 'core',
  gce-inventory:list         ansible_python_interpreter: 'PATH=/home/core/bin:$PATH python' } },
  gce-inventory:list   ansible_ssh_host: '/externalIP',
  gce-inventory:list   order: [ 'zone', 'tags', 'machine_type', 'status' ] } +12ms
  gce-inventory:hostvars hostvar(status) selects /status and uses transform(lowercase) +4ms
  gce-inventory:hostvars hostvar(network) selects /networkInterfaces/0/network and uses captureRe([^/]+(?=/$|$)) +0ms
  gce-inventory:hostvars hostvar(internalIP) selects /networkInterfaces/0/networkIP +0ms
  gce-inventory:hostvars hostvar(externalIP) selects /networkInterfaces/0/accessConfigs/0/natIP +0ms
  gce-inventory:hostvars hostvar(tags) selects /tags/items +0ms
  gce-inventory:hostvars hostvar(metadata) selects /metadata/items and uses transform(objectFromKeyValues) +0ms
  gce-inventory:hostvars hostvar(machine_type) selects /machineType and uses captureRe([^/]+(?=/$|$)) +0ms
  gce-inventory:fetch started fetching host vars and accumulating groups +1ms
  gce-inventory:fetch started getting vms for zone(europe-west1-b) +3ms
Error: invalid_request
    at Request._callback (/usr/lib/node_modules/gce-inventory/node_modules/google-auth-library/lib/transporters.js:81:15)
    at Request.self.callback (/usr/lib/node_modules/gce-inventory/node_modules/google-auth-library/node_modules/request/request.js:187:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/usr/lib/node_modules/gce-inventory/node_modules/google-auth-library/node_modules/request/request.js:1044:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (/usr/lib/node_modules/gce-inventory/node_modules/google-auth-library/node_modules/request/request.js:965:12)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
---```

thanks in advance
